### ISSUE TITLE
Do you have examples?

### ISSUE THREAD

**Issue by jesse1983** [marko-js/jest#1]
Tks!

**Comment by tigt** [comment]
[The README](https://github.com/marko-js/jest/blob/master/README.md) has been updated; do its examples answer your question?

**Comment by DylanPiercey** [comment]
@jesse1983 is the README sufficient or were you looking for real world examples?

**Comment by arinthros** [comment]
> @jesse1983 is the README sufficient or were you looking for real world examples?

@DylanPiercey I'm super new to Marko, but I use Jest in my React projects. Do you have any real-world examples of @marko/jest + @marko/testing-library tests and mocks in the wild? That would be super helpful.
